### ISSUE TITLE
Missing Pinterest data-pin-url

### ISSUE THREAD

**Issue by w3work** [CodyHouse/cd-social-sharing-changelog#1]
Hi CodyHouse Team,

i use the "Social Sharing" Component inside a blog article. After customizing the urls, description and images for each social media platform, i figured out that for Pinterest no URL is set.
Here only Image and Description is save, but no link to my blog article is set on the Pin.

Is it possible that you add this function? :)

Regards
Sven

**Comment by claudia-romano** [comment]
Hi Sven, thanks for the heads-up!
We have just pushed a new version of the component with the additional data-url for Pinterest. More details on the Info page:
https://codyhouse.co/ds/components/info/social-sharing#pinterest

Cheers!
